### ISSUE TITLE
Van Cittert iterations

### ISSUE THREAD

**Issue by Abhishek-dev18** [Abhishek-dev18/Image-De-blurring#3]
De-blurring using Van Cittert iterations

**Comment by archydas** [comment]
[Van cittert.docx](https://github.com/Abhishek-dev18/Image-De-blurring/files/14610693/Van.cittert.docx)

**Comment by archydas** [comment]
[algorithm_van_cittert.docx](https://github.com/Abhishek-dev18/Image-De-blurring/files/14610697/algorithm_van_cittert.docx)
