### ISSUE TITLE
Explanation/Flowchart/Algorithm/Summary

### ISSUE THREAD

**Issue by Abhishek-dev18** [Abhishek-dev18/Image-De-blurring#5]
-> Quality Index of Image- PSNR, SNR, SSIM, MSE
-> Dataset- GoPro
-> Block diagram
-> Algorithm
-> Flowchart
->Explanation

**Comment by archydas** [comment]
[performance metrics.docx](https://github.com/Abhishek-dev18/Image-De-blurring/files/14563998/performance.metrics.docx)

**Comment by archydas** [comment]
[performance metrics.docx](https://github.com/Abhishek-dev18/Image-De-blurring/files/14564079/performance.metrics.docx)

**Comment by archydas** [comment]
[psnr.docx](https://github.com/Abhishek-dev18/Image-De-blurring/files/14592042/psnr.docx)

**Comment by archydas** [comment]
[snr.docx](https://github.com/Abhishek-dev18/Image-De-blurring/files/14592074/snr.docx)

**Comment by archydas** [comment]
[mse.docx](https://github.com/Abhishek-dev18/Image-De-blurring/files/14592135/mse.docx)

**Comment by archydas** [comment]
[richardson-lucy.docx](https://github.com/Abhishek-dev18/Image-De-blurring/files/14611914/richardson-lucy.docx)
algorithm for Richardson lucy deconvolution

**Comment by archydas** [comment]
[FLOWCHART1.docx](https://github.com/Abhishek-dev18/Image-De-blurring/files/14611931/FLOWCHART1.docx)
flowchart for the Richardson lucy deconvolution technique

**Comment by archydas** [comment]
[algorithm_van_cittert.docx](https://github.com/Abhishek-dev18/Image-De-blurring/files/14611937/algorithm_van_cittert.docx)
Algorithm for the Van Cittert iterations

**Comment by archydas** [comment]
[weiner filter algorithm.docx](https://github.com/Abhishek-dev18/Image-De-blurring/files/14611947/weiner.filter.algorithm.docx)
algorithm for the weiner filter technique
